#!/bin/bash

METAFILE="$2"

function pre {
  bv=$(compgen -v)
  . /etc/rid/env || { echo "Failed to source /etc/rid/env"; exit 1; }
  . /etc/rid/meta/"$METAFILE" || { die "Failed to source /etc/rid/meta/$METAFILE"; exit 1; }
  av=$(compgen -v)

  unset BUILD_FAILED
}

function cleanup {
  for var in $av; do
    if ! echo "$bv" | grep -q "^$var$"; then
      unset "$var"
    fi
  done
  rm -rf /tmp/rid/building/$NAME-$VERS
}

function ins {
  check_perms
  pushd /tmp/rid/building/$NAME-$VERS > /dev/null || { die "Failed to enter installation directory"; exit 1; }

  echo "Installing $NAME-$VERS..."
  eval "$IDIR"
}

function rem {
  check_perms

  echo "Removing $NAME-$VERS..."
  eval "$RDIR"
}

function check_perms {
  if [ "$EUID" -ne 0 ]; then
    die "Insufficient permissions"
  fi
}

function alert_failed {
    echo "BUILD FAILED FOR $NAME-$VERS" >&2
    export BUILD_FAILED=true
}

pre
case $1 in
  i)
    ins || alert_failed
    popd > /dev/null
    cleanup
    ;;
  r)
    rem
    cleanup
    ;;
  u)
    if [ -z "$UDIR" ]; then
      echo "Updating $NAME (default)..."
      ins
    else
      echo "Updating $NAME (custom)..."
      eval "$UDIR"
    fi
    cleanup
    ;;
  s)
    echo "Status of $NAME-$VERS: $STAT"
    cleanup
    ;;
  v)
    echo "NAME: $NAME"
    echo "VERS: $VERS"
    echo "LINK: $LINK"
    echo "STAT: $STAT"
    echo "DEPS: $DEPS"
    echo ""
    echo "IDIR: $IDIR"
    echo "RDIR: $RDIR"
    echo "UDIR: $UDIR"
    ;;
  *)
    echo "Invalid action: $2"
    echo "Valid actions:"
    echo "i - install"
    echo "r - remove"
    echo "u - update"
    echo "s - status"
    echo "v - variables"
    exit 1
    ;;
esac
