#!/bin/bash
# mn = meson, ninja
# mn wraps the configure, build, and install process for 64-bit packages
# any arguments passed to it are interpreted as meson arguments

DESTDIR=
mkdir -pv ridbuild        &&
cd        ridbuild        &&

meson setup ..             \
  --prefix=/usr            \
  --buildtype=release      \
  --strip                  \
  "$@"                    ||
die "Meson setup failed"

ninja                     ||
die "Ninja failed"

ninja install             ||
die "Ninja install failed"
