#!/bin/bash
# mn = meson, ninja
# mn wraps the configure, build, and install process for 64-bit packages
# any arguments passed to it are interpreted as meson arguments

CFGPATH="."
if [ -z $RIDBUILD ]; then
  mkdir -pv ridbuild      &&
  cd        ridbuild      &&
  CFGPATH=".."
fi

meson setup $CFGPATH       \
  --prefix=/usr            \
  --buildtype=release      \
  --strip                  \
  "$@"                    ||
die "Meson setup failed"

ninja                     ||
die "Ninja failed"

DESTDIR= ninja install    ||
die "Ninja install failed"
