[package]
name = "rid"
version = "0.16.3" # added and removed options :(
edition = "2021"

[features]
offline = []
default = []

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
glob = "0.3.1"
indicatif = "0.17.8"
lazy_static = "1.5.0"
regex = "1.11.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
ureq = "2.10.1"
whoami = { version = "1.5.2", default-features = false }
