[package]
name = "rid"
version = "0.1.2"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
lazy_static = "1.5.0"
regex = "1.11.0"
reqwest = { version = "0.12.8", features=["blocking"] }
whoami = { version = "1.5.2", default-features = false }
