[package]
name = "rid"
version = "0.17.0" # removal of bootstrap-related flags and introduction of install.sh, removal of release.sh
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
indicatif = "0.17.8"
lazy_static = "1.5.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
ureq = "2.10.1"
whoami = { version = "1.5.2", default-features = false }
