[package]
name = "rid"
version = "0.11.4"
edition = "2021"

[features]
offline = []
default = ["reqwest"]

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
glob = "0.3.1"
lazy_static = "1.5.0"
regex = "1.11.0"
reqwest = { version = "0.12.8", features = ["blocking"], optional = true }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
whoami = { version = "1.5.2", default-features = false }
