[package]
name = "rid"
version = "0.20.0" # full rewrite, merged stabs
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
indicatif = "0.17.8"
lazy_static = "1.5.0"
rayon = "1.10.0"
regex = "1.11.1"
scraper = "0.21.0"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.132"
ureq = "2.10.1"
whoami = { version = "1.5.2", default-features = false }
