[package]
name = "rid"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.19", features = ["derive"] }
lazy_static = "1.5.0"
project-root = "0.2.2"
regex = "1.11.0"
whoami = { version = "1.5.2", default-features = false }
