# rid config

[linkval]
retry_count = 3 # limited to 128, though you shouldn't go that high anyway
stack_size = 128 # in kb
thread_count = 128

[upstream]
retry_count = 3
stack_size = 512 # in kb
thread_count = 64

[colors] # ascii escape codes (\x1b[ is accounted for)
danger = "31;1m  "
default = "30;3m"
message = "36;1m  "
prompt = "35;1m"
stderr = "31;3;1m"
verbose = "34;1m"

[behavior]
remove_tarballs = false # whether to remove tarballs when removing a package
search_threshold = 3 # levenshtein (edit) distance
