#!/bin/bash
NAME="cmake"
VERS=3.30.4
ver="${VERS%.*}"
LINK="https://cmake.org/files/v$ver/cmake-$VERS.tar.gz"


IDIR=$(cat <<EOF

unpriv bash << 'priv'
sed -i '/"lib64"/s/64//' Modules/GNUInstallDirs.cmake &&

./bootstrap --prefix=/usr          \
            --system-libs          \
            --mandir=/share/man    \
            --no-system-jsoncpp    \
            --no-system-cppdap     \
            --no-system-librhash   \
            --no-system-libarchive \
            --no-system-libuv      \
            --no-system-nghttp2    \
            --docdir=/share/doc/cmake-$VERS &&
make
priv

make install

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
