#!/bin/bash
NAME="curl"
VERS=8.10.1
LINK="https://curl.se/download/curl-$VERS.tar.xz"
DEPS="libpsl"


IDIR=$(cat <<EOF

./configure --prefix=/usr                           \
            --disable-static                        \
            --with-openssl                          \
            --with-ca-path=/etc/ssl/certs &&
make
make install &&

rm -rf docs/examples/.deps &&

find docs \( -name Makefile\* -o  \
             -name \*.1       -o  \
             -name \*.3       -o  \
             -name CMakeLists.txt \) -delete &&

cp -v -R docs -T /usr/share/doc/curl-$VERS

cd /tmp/building
rm -rf curl-$VERS
tar xvf /etc/rid/sources/curl-$VERS.tar.xz

CC="gcc -m32" CXX="g++ -m32"           \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig   \
./configure --prefix=/usr              \
            --libdir=/usr/lib32        \
            --host=i686-pc-linux-gnu   \
            --disable-static           \
            --with-openssl             \
            --with-ca-path=/etc/ssl/certs &&

make
make DESTDIR=$PWD/DESTDIR install
cp -vr DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR
ldconfig

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
