#!/bin/bash
NAME="libpsl"
VERS=0.21.5
LINK="https://github.com/rockdaboot/$NAME/releases/download/$VERS/$NAME-$VERS.tar.gz"
DEPS="libidn2 libunistring"


IDIR=$(cat <<EOF

mkdir build &&
cd    build &&

meson setup --prefix=/usr --buildtype=release --strip &&

ninja
ninja install

rm -rf *
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
meson setup ..                       \
      --prefix=/usr                  \
      --libdir=/usr/lib32            \
      --strip                        \
      --buildtype=release &&

ninja
DESTDIR=$PWD/DESTDIR ninja install
cp -vr DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR
ldconfig

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
