#!/bin/bash
NAME="libtasn1"
VERS=4.19.0
LINK="https://ftp.gnu.org/gnu/$NAME/$NAME-$VERS.tar.gz"
DEPS=""


IDIR=$(cat <<EOF

./configure --prefix=/usr --disable-static &&
make
make install

make distclean
CC="gcc -m32" CXX="g++ -m32"         \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig \
./configure --prefix=/usr            \
            --libdir=/usr/lib32      \
            --host=i686-pc-linux-gnu \
            --disable-static &&

make
make DESTDIR=$PWD/DESTDIR install
cp -vr DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR
ldconfig

EOF
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
