#!/bin/bash
NAME="p11-kit"
VERS=0.25.5
LINK="https://github.com/p11-glue/$NAME/releases/download/$VERS/$NAME-$VERS.tar.xz"
DEPS="libtasn1 nss"


IDIR=$(cat <<'~fin.'

sed '20,$ d' -i trust/trust-extract-compat &&

cat >> trust/trust-extract-compat << "EOF"
# Copy existing anchor modifications to /etc/ssl/local
/usr/libexec/make-ca/copy-trust-modifications

# Update trust stores
/usr/sbin/make-ca -r
EOF

mkdir p11-build &&
cd    p11-build &&

meson setup ..            \
      --prefix=/usr       \
      --buildtype=release \
      --strip             \
      -D trust_paths=/etc/pki/anchors &&
ninja

ninja install &&
ln -sfv /usr/libexec/p11-kit/trust-extract-compat \
        /usr/bin/update-ca-certificates

rm -rf *
CC="gcc -m32" CXX="g++ -m32"                     \
PKG_CONFIG_PATH=/usr/lib32/pkgconfig             \
CFLAGS+=" -Wno-error=incompatible-pointer-types" \
meson setup ..                                   \
      --prefix=/usr                              \
      --libdir=/usr/lib32                        \
      --buildtype=release                        \
      --strip                                    \
      -Dtrust_paths=/etc/pki/anchors &&

ninja

DESTDIR=$PWD/DESTDIR ninja install
cp -vr DESTDIR/usr/lib32/* /usr/lib32
rm -rf DESTDIR
ldconfig

ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib/libnssckbi.so
ln -sfv ./pkcs11/p11-kit-trust.so /usr/lib32/libnssckbi.so

~fin.
)

RDIR=$(cat <<EOF

echo not implemented

EOF
)

UDIR=$(cat <<EOF
EOF
)
