#!/bin/bash

NAME="tree"
VERS=2.1.3
LINK="https://gitlab.com/OldManProgrammer/unix-tree/-/archive/$VERS/unix-tree-$VERS.tar.bz2"
STAT="installed"
DEPS=""


IDIR=$(cat <<EOF

make
make PREFIX=/usr MANDIR=/usr/share/man install

EOF
)

RDIR=$(cat <<EOF

rm -vf /usr/bin/tree

EOF
)

UDIR=$(cat <<EOF

#
echo "Awesome custom update directions"

EOF
)
